on:
  push:
    branches:
      - 1.x
  pull_request: ~

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2']
      stability: >-
        ['prefer-stable']
